## Convolutions

In [44]:
import numpy as np

x = np.random.randint(0, 10, size=(6, 6)) 
x

array([[1, 8, 7, 3, 3, 3],
       [3, 8, 5, 9, 2, 6],
       [0, 6, 0, 0, 4, 6],
       [2, 0, 3, 3, 5, 3],
       [1, 3, 5, 3, 6, 6],
       [2, 7, 8, 5, 4, 3]])

In [5]:
f3 = np.random.randint(-3, 3, size=(3, 3)) 
f3

array([[ 1,  0,  0],
       [ 2,  1,  0],
       [-2,  2, -1]])

In [6]:
f5 = np.random.randint(-3, 3, size=(5, 5)) 
f5

array([[ 1,  0,  0, -1, -2],
       [ 2, -2,  0, -3, -2],
       [-1,  0, -3,  1,  0],
       [-1, -2,  0, -3,  2],
       [ 0,  2,  1, -3,  0]])

Calculate via code the convolutional output of the above array and the filters `f3` and `f5` assuming:
 - `padding="valid"`
 - `padding="same"` (see if `np.pad()` helps)
 
Also, calculate using `Conv2d` layer.

## Pooling

In [24]:
x = np.random.randint(-10, 10, size=(6, 6)) 
x

array([[  0,   3,  -3,   4,   1,   5],
       [ -9,  -9,   4,   2,   6,   7],
       [-10,   3, -10,  -4,  -5, -10],
       [ -1,  -4,  -2,  -8,   2,   2],
       [ -4,   7,   5,  -3,  -4,   3],
       [ -2,  -1,   5,  -9, -10,   8]])

Calculate the output of a pooling operation assuming no padding and using a pooling layer:
 - `pool_size = (2, 2)` and `strides=2` and *Max Pooling* is used
 - `pool_size = (3, 3)` and `strides=2` and *Max Pooling* is used
 - `pool_size = (2, 2)` and `strides=1` and *Max Pooling* is used
 - `pool_size = (3, 3)` and `strides=1` and *Max Pooling* is used
 - `pool_size = (2, 2)` and `strides=2` and *Average Pooling* is used
 - `pool_size = (3, 3)` and `strides=2` and *Average Pooling* is used
 - `pool_size = (2, 2)` and `strides=1` and *Average Pooling* is used
 - `pool_size = (3, 3)` and `strides=1` and *Average Pooling* is used


## Parameter calculation

How many trainable parameters does the following model have: 

- input data has dimensions (180, 180, 3)
- Conv2D(32, kernel_size=(5, 5), activation="relu")
- AveragePooling(pool_size=(2, 2), strides=2)
- Conv2D(32, kernel_size=(5, 5), activation="relu")
- AveragePooling(pool_size=(2, 2), strides=2)
- Flatten()
- Dense(128, activation="relu")
- Dense(3, activation="softmax")

Create fully-connected and convolutional neural networks using both the **sequential** and the **functional** API's in Keras.

What does **Early Stopping** mean and why do we use it?

What do we mean by the **receptive field** of a filter in a convolutional neural network?

What 2 properties do convolutional neural networks have that make them much more useful for images than fully-connected networks?

Explain **padding**.

Explain **strides**.

What is the purpose of a **pooling** layer?

What is the difference between a **parameter** and a **hyperparameter**?

What are training, validation, and test datasets used for?

What is a baseline and how is it used?

What are the first 2 goals we should have when creating a deep learning model?

What are some ways to deal with overfitting?

In order to get the best model you first have to....

What are some common problems when training a model and how can they be overcome?